### ISSUE TITLE
Quick (hopefully) question

### ISSUE THREAD

**Issue by genyded** [pusher-community/realtime-twitter-search-vuejs#1]
Hi Jack,

This really isn't an 'issue' per se, but I am curious if there is a reason you not using webpacks HMR and opted for Node's live server instead? Also is there a reason whichever you use is not being proxied removing the need to run 2 processes manually? 

BTW - great [article](http://blog.pusher.com/exploring-real-time-apps-with-vuejs-es2016-and-webpack/) and repo!!! We're just learning Vue in prep for an upcoming large project and 99% of the stuff out there is outdated, and/or using ES5 with Browserify. Your work should really help us jump start what we need for our project and is very much appreciated!

Dale

**Comment by jackfranklin** [comment]
I didn't want to bog the article down even more with Webpack specifics; plus I personally often stick to just live reloading rather than HMR, and also keep the setup simple  and just run two commands rather than proxy.

That said, if you fancied making those changes I'd love to see the PR, so we can improve this repo for all that use it. I'm really pleased that this has helped you !
